apiVersion: v1
kind: Service
metadata:
  name: oo3h
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: "oo3h"
    port: 8080
  selector:
    app: oo3h
